# Generated by Django 6.0.1 on 2026-01-25 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpPermitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField(unique=True)),
                ('esta_permitida', models.BooleanField(default=True)),
                ('equipo_nombre', models.CharField(max_length=100)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('navegador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='visitantes/')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('a_quien_visita', models.CharField(max_length=200)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('normal', 'Normal'), ('lista_negra', 'Lista Negra'), ('vip', 'VIP'), ('delagro', 'Delagro'), ('reserva', 'Reserva')], default='normal', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
                ('ip_origen', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_seguridad', models.CharField(max_length=255)),
                ('respuesta_seguridad', models.CharField(max_length=255)),
                ('esta_bloqueado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
