# Generated by Django 6.0.1 on 2026-01-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='a_quien_visita',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='salida',
        ),
        migrations.AlterField(
            model_name='visitante',
            name='estatus',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('empleado', 'Empleado'), ('externo', 'Empresa Externa'), ('denegado', 'Acceso Denegado')], default='natural', max_length=20),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('a_quien_visita', models.CharField(max_length=200)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='visitas.visitante')),
            ],
        ),
    ]
