# Generated by Django 6.0.1 on 2026-01-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_remove_visitante_a_quien_visita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
