# Generated by Django 6.0.1 on 2026-01-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_ipactiva'),
    ]

    operations = [
    ]
