# Generated by Django 6.0.1 on 2026-01-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0004_add_logging_signals'),
        ('visitas', '0004_auto_20260127_2123'),
    ]

    operations = [
    ]
