# Generated by Django 6.0.1 on 2026-02-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0007_registrointento_delete_intentologin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrointento',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
#        migrations.DeleteModel(
#            name='IntentoLogin',
#        ),
    ]
